<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>start_datePicker</name>
   <tag></tag>
   <elementGuidId>3310d7c1-5fe8-45b7-a75e-799df0015fcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/section/div[1]/div[2]/div/div/div[3]/form/div/div[2]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.calicon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f15f24bf-9332-467e-a07b-92f7a15e43f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calicon</value>
      <webElementGuid>4be2396d-a61f-4b6e-bc57-4a178ad07c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>document.getElementById('from').focus();</value>
      <webElementGuid>02d66264-7319-4697-bae6-ba0be02df3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/icon/calendar.png</value>
      <webElementGuid>52722b64-0a3d-423b-9e83-cd0d6dbbde18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slideshow&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;table-wrapper full-width&quot;]/div[@class=&quot;table-cell&quot;]/div[@class=&quot;search-box&quot;]/form[@class=&quot;ng-pristine ng-valid ng-scope&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-2&quot;]/div[@class=&quot;form-group&quot;]/img[@class=&quot;calicon&quot;]</value>
      <webElementGuid>c6add3b4-cba2-4a33-9153-d384abd38899</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@onclick=&quot;document.getElementById('from').focus();&quot;]</value>
      <webElementGuid>4e206805-646e-4368-8d45-7bf42663a185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slideshow']/div[2]/div/div/div[3]/form/div/div[2]/div/img</value>
      <webElementGuid>c6aa75d4-1810-444b-a60e-e3987dbf4384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>43beeba2-99aa-4d75-a957-36c9e5613221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/icon/calendar.png']</value>
      <webElementGuid>f7f19cba-22a3-458a-b555-b5f1bd127020</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
