<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Detail  Edit</name>
   <tag></tag>
   <elementGuidId>e41fce45-c4f5-45f9-ab56-b431919ba9b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='edit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e3720930-6224-46ab-8917-f9b57a0d06cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit</value>
      <webElementGuid>b1401850-3537-4b40-82e7-88f7870e7fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>5450e26e-4649-425a-8687-412716e55e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-iddata</name>
      <type>Main</type>
      <value>4083</value>
      <webElementGuid>847ba265-ac5a-405c-b3a8-933f32e9cf3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productid</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>6086014a-3a5a-4d69-88c9-d9359310f1f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-jeniskendaraanid</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>75f38de4-88a3-45df-99fc-1d8e8b4f35ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-kondisikendaraanid</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>a6e78ef8-5f25-406b-8195-6c08ec0880ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-usiakendaraanlunasmin</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>6c65ae0e-cdc2-41db-baa0-2f5a14f74be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-usiakendaraanlunasmax</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>d56124f3-e817-4b0b-b2dd-5c8fa61609aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-startberlaku</name>
      <type>Main</type>
      <value>2022-01-10</value>
      <webElementGuid>a93d5242-2aba-447f-8dde-fa4d7c497426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-endberlaku</name>
      <type>Main</type>
      <value>2022-12-31</value>
      <webElementGuid>56eb301b-9d71-4ea6-9339-8618e5fafe2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loantype</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ad696618-1b1a-45ce-8e18-49bf9e10d262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-statusapproval</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f7e2cf51-dc0a-4d79-bbc4-af5dcf29e12b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tenor1</name>
      <type>Main</type>
      <value>5100000</value>
      <webElementGuid>e7ccfed7-aa1b-49f8-98db-f47f1e5247fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tenor2</name>
      <type>Main</type>
      <value>5100000</value>
      <webElementGuid>ceda2083-7d84-4416-9bb6-bffc2623ac25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tenor3</name>
      <type>Main</type>
      <value>5100000</value>
      <webElementGuid>dfa38bb8-736c-49a1-b61b-d248aa1b69de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tenor4</name>
      <type>Main</type>
      <value>5100000</value>
      <webElementGuid>0b9bb518-7a84-43f6-80d1-6609129f1eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tenor5</name>
      <type>Main</type>
      <value>5100000</value>
      <webElementGuid>00f9c98e-446c-4123-9e2d-7df14e4ed1dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#formEdit</value>
      <webElementGuid>397886bc-63d7-4fa8-834f-a56b531b5d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success btn-sm</value>
      <webElementGuid>7b1a9b71-cd3d-4e8b-9c95-8d539217f9a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Detail / Edit</value>
      <webElementGuid>32a21a1a-128b-4845-927c-b2143e89d094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/table[1]/tbody[1]/tr[1]/td[@class=&quot;kontentop&quot;]/table[1]/tbody[1]/tr[1]/td[2]/table[@class=&quot;tbllogin&quot;]/tbody[1]/tr[2]/td[@class=&quot;kontentd&quot;]/table[@class=&quot;table table-striped table-hover&quot;]/tbody[1]/tr[1]/td[12]/a[@id=&quot;edit&quot;]</value>
      <webElementGuid>c5541188-3b72-4c63-a617-13482adf883c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='edit']</value>
      <webElementGuid>ebc34a25-fa86-4324-a6e2-98884a3723e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Detail / Edit')]</value>
      <webElementGuid>f83a1ec9-6335-4f08-804b-0e0a1aeb8b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Used'])[1]/following::a[1]</value>
      <webElementGuid>fa0f17c6-ce6f-4471-9436-5c2c641fffef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passenger'])[1]/following::a[1]</value>
      <webElementGuid>55028076-7153-4757-95a0-2f96ca0a6406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::a[1]</value>
      <webElementGuid>06da4042-dd75-4eb0-b12e-fa948a6d228b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADDM'])[2]/preceding::a[2]</value>
      <webElementGuid>f576b122-912e-48aa-a5e6-e5634fb2ce02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Detail / Edit']/parent::*</value>
      <webElementGuid>5c09651a-4013-49be-9478-df597569cfc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[62]</value>
      <webElementGuid>1f441dc1-f1cc-4bee-b6ff-c846c8848bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[12]/a</value>
      <webElementGuid>ec596b72-37ea-424e-b2f5-5668a0cfd509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'edit' and (text() = 'Detail / Edit' or . = 'Detail / Edit')]</value>
      <webElementGuid>1a8018ef-3a9f-4c9d-97e3-9829457dc2ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
