<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_txtusername</name>
   <tag></tag>
   <elementGuidId>216357fc-8b16-4275-9ccb-2b86283e27ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='txtusername']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;txtusername&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d63951fd-4345-489b-82a7-055449df8fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>44d5a065-2f67-41be-85dd-9634522624ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtusername</value>
      <webElementGuid>dfd7ebfd-e02b-40ab-98b1-bd19a492b61d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtlogin</value>
      <webElementGuid>a0a357dc-3499-4d76-a3df-2b1faff3740c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/table[@class=&quot;tbllogin&quot;]/tbody[1]/tr[2]/td[@class=&quot;center&quot;]/table[1]/tbody[1]/tr[2]/td[1]/input[@class=&quot;txtlogin&quot;]</value>
      <webElementGuid>4d1f6a4a-05bb-4578-9d6a-a4be40f97bd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='txtusername']</value>
      <webElementGuid>cae6c187-38fe-450d-9f63-33d92389ac85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>5b5d8686-e618-4f65-906e-356a6bc3f45c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txtusername']</value>
      <webElementGuid>d68b352e-4e52-4b15-be0b-c00fbf165043</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
