<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start  End Berlaku_startBerlaku</name>
   <tag></tag>
   <elementGuidId>425c28c6-a5fe-4888-ac8e-f82f59bc62ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='startBerlaku']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#startBerlaku</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f04e3ca-93c1-485e-b558-f77455a0d210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>64029c82-0141-44a9-b003-4cf0d052365c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm hasDatepicker</value>
      <webElementGuid>4bff9ca9-d938-4c35-9988-56d89a4e083d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>startBerlaku</value>
      <webElementGuid>375dd77b-042c-436e-ba30-7897a71a6b50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>startBerlaku</value>
      <webElementGuid>f18b533a-715f-475d-a4fd-a1d728a26def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>YYYY-MM-DD</value>
      <webElementGuid>6d2c2ad1-9a3e-4727-b5dd-c07b31974a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>cekTahunBerlaku()</value>
      <webElementGuid>5e892b17-bbb8-4d29-bdaf-0af6b0491b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startBerlaku&quot;)</value>
      <webElementGuid>ba817e85-0199-48af-9aaa-0a04e175a698</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='startBerlaku']</value>
      <webElementGuid>19689c05-dc0a-4f77-bdf7-81ff43c4a8df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/div/div[16]/div/div/input</value>
      <webElementGuid>5d4c7ae7-3d1d-44f5-aeb3-eca6f9ef8b7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div/input</value>
      <webElementGuid>ff4e6a21-9daf-41c6-8358-abf715f44855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'startBerlaku' and @name = 'startBerlaku' and @placeholder = 'YYYY-MM-DD']</value>
      <webElementGuid>b65fec08-b4b0-48a2-9740-09c4105e47be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
